files: \.(py)$
default_stages: [commit, manual]
repos:

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
    - id: ruff
      args: [
      --fix,
      --unsafe-fixes,
      --exit-non-zero-on-fix,
      --target-version, "py312",
      --select, "ALL",
      --ignore, "ASYNC101,D,E501,S311,T201"
      ]
    - id: ruff-format

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
    - id: mypy
      additional_dependencies: [types-requests]
      stages: [manual]

-   repo: https://github.com/dosisod/refurb
    rev: v2.0.0
    hooks:
    - id: refurb
      args: [--python-version, "3.12"]
      stages: [manual]

