files: \.(py)$
default_stages: [commit, manual]
repos:

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
    - id: ruff
      args: [
      --fix,
      --unsafe-fixes,
      --exit-non-zero-on-fix,
      --target-version, "py312",
      --select, "ALL",
      --ignore, "BLE001,D,E501,S311"
      ]
    - id: ruff-format

-   repo: https://github.com/dosisod/refurb
    rev: v1.24.0
    hooks:
    - id: refurb
      args: [--python-version, "3.12"]
      stages: [manual]

